use_frameworks!

platform :ios, '13.0'

target 'ZZCustomControl_Example' do
  pod 'ZZCustomControl', :path => '../ZZCustomControl.podspec'
  pod 'ZZBase', '~> 1.1.0'
  target 'ZZCustomControl_Tests' do
    inherit! :search_paths

    #pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
