use_frameworks!

platform :ios, '10.0'

target 'ZZCustomControl_Example' do
  pod 'ZZCustomControl', :path => '../'

  target 'ZZCustomControl_Tests' do
    inherit! :search_paths

    pod 'FBSnapshotTestCase' , '~> 2.1.4'
  end
end
